### ISSUE TITLE
Add validation for safely deletion of SubNamespace

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/accurate#22]
## What

When a SubNamespace is deleted, a related Namespace is deleted by the accurate controller.

However, sometimes the Namespace deletion does not complete, and it remains terminating.
At this time, the owner of the SbuNamespace may not manage the terminating namespace.

The reason why the Namespace cannot be deleted is that some namespaced resources in it cannot be deleted due to the finalizer or any other reasons.

## How

Add validation when deleting a SubNamespace.
If there are any namespaced resources left in the related namespace, deny the deletion.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
It seems that no one is interested in implementing this. Closing.
