### ISSUE TITLE
[helm] `namingPolicies` in values.yaml is not reflected in configmap

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/accurate#41]
**Describe the bug**

NamingPolicy is now supported in #17.
However, `namingpolicies` in values.yaml is not reflected in configmap.

Because `namingpolicies` is not described in configmap.yaml.
https://github.com/cybozu-go/accurate/blob/da7508cf549fd7c49668d515e759345d6c6824a6/charts/accurate/templates/configmap.yaml

**Environments**
- Version: 0.3.0
- Chart Version: 0.2.2

**To Reproduce**
1. Prepare a values.yaml containing `namingPolicies` as below:

```yaml
controller:
  config:
    namingPolicies:
      - root:  foo
        match: foo_.*
```

2. Deploy accurate using Helm with the values.yaml.

```
helm install --create-namespace --namespace accurate accurate -f values.yaml accurate/accurate
```

3. The generated configmap does not contain `namingPolicies`

**Expected behavior**
The configmap should contain `namingPolicies`.

**Comment by ymmt2005** [comment]
Fixed in #42
