### ISSUE TITLE
Declare GA and release v1.0.0

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/accurate#52]
## What

We have been using accurate in production environments for a while.
Since there are no high priority issues, let's declare GA status and release v1.0.0.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by erikgb** [comment]
@ymmt2005 I think this issue can be closed? Or are we waiting for the Helm chart to become GA? Ref. https://github.com/cybozu-go/accurate/releases/tag/v1.2.1

**Comment by ymmt2005** [comment]
ah, yes, this can be closed. Thank you.
