### ISSUE TITLE
SubNamespace should be compatible with kstatus

### ISSUE THREAD

**Issue by erikgb** [cybozu-go/accurate#85]
## What

We use FluxCD to provision our clusters, and FluxCD supports [health checks](https://fluxcd.io/flux/components/kustomize/kustomizations/#health-checks) for CRDs compatible with [kstatus](https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/kstatus/README.md). And I believe ArgoCD also does this.

It would be nice if the SubNamespace CRD had a status subresource compatible with kstatus. You can read more details in the specification, but I would suggest the following requirements (at least as a start):

- A SubNamespace with empty status has not yet been picked up by the controller
- The controller should ensure `.status.obeservedGeneration` is equal to `.metadata.generation` when reconciling a SubNamespace
- If the actual state differs from the desired state, the controller should add status conditions indicating that a reconcile is in progress
- When the actual state equals the desired status, the controller should remove all status conditions
- If the controller is unable to reconcile successfully for any reason, like in a conflict situation, the controller should add conditions indicating what's wrong.

Since the `status` field on SubNamespace currently is a simple string, this will be a **breaking change of status**.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zeroalphat** [comment]
@erikgb 
Thanks for your feedback.
We will investigate it.

**Comment by ymmt2005** [comment]
To address this, we need to make an incompatible change to the API.
I mean, we need to cut `v2`.
