### ISSUE TITLE
Webhooks should have better names

### ISSUE THREAD

**Issue by erikgb** [cybozu-go/accurate#86]
## What

When attempting to delete a namespace with subnamespaces, this is rejected by the webhook - which is good. But I think webhooks should be named properly - so a user can understand better what's going on.

````shell
$ k delete namespaces erikbo
Error from server (Forbidden): admission webhook "vnamespace.kb.io" denied the request: child namespaces exist
````

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zeroalphat** [comment]
@erikgb 
As your feedback, it looks like it should be fixed.
We will fix it.
