### ISSUE TITLE
docs: better example for propagate generated

### ISSUE THREAD

**Issue by erikgb** [cybozu-go/accurate#93]
## What

The example of using propagate-generated is outdated: https://github.com/cybozu-go/accurate/blob/6cd77bf7e5e5fc99316e6b165c0096aa3cb050e5/docs/propagation.md?plain=1#L32-L52

As both cert-manager and sealed-secrets support adding labels/annotations to dependents:

- cert-manager [secretTemplate](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSecretTemplate)
- sealed-secrets [template](https://github.com/bitnami-labs/sealed-secrets#sealedsecrets-as-templates-for-secrets)

## How

I actually wanted to submit a PR to update the docs with a more relevant example, but I am struggling to find any public operator that creates dependents **without** the ability to configure the owner to add labels/annotations to the dependents. So in order to resolve this doc issue, a good example of using this feature is required.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Thank you for raising this issue.
We are checking if there are other uses on our side.
