### ISSUE TITLE
Should clean up previously propagated namespace labels/annotations

### ISSUE THREAD

**Issue by erikgb** [cybozu-go/accurate#98]
## What

Ref. [docs](https://cybozu-go.github.io/accurate/subnamespaces.html#setting-a-namespace-as-a-root-namespace):

> Accurate currently does not delete previously propagated labels when deleted from the parent namespace to prevent unintended deletions. Users are expected to manually delete labels/annotations that are no longer needed.

I wonder which kind of "unintended deletions" are referred to here. I would expect Accurate to clean up a previously propagated namespace label/annotation (based on Kubernetes `managedFields` ownership) when the desired state of parent/template NS (or SubNamespace) indicates that a label/annotation should not be propagated.

Could a migration to SSA (Server Side Apply) aid in this? Since controller-runtime still has limited support for SSA, ref. https://github.com/kubernetes-sigs/controller-runtime/issues/347, we probably must migrate to `Unstructured` instead of structured types. But IMO I think it would be worth it.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
> Could a migration to SSA (Server Side Apply) aid in this?

I think so.
